10# maxTimeDelay: 604799
testMode: dapptest
# sender: ["0x0000000000000000000000000000000000000001"]
multi-abi: true
allContracts: true
cryticArgs: ['--solc-remaps', '@=node_modules/@']
# testMaxGas: 80000300000
# balanceAddr: 0xffffffffffffffff
codeSize: 0xffffffffffffffff
testLimit: 50000
# seqLen: 10000
# allowFFI: true
shrinkLimit: 500000